### ISSUE TITLE
Methods to print stack traces of all ULTs in a core dump

### ISSUE THREAD

**Issue by smseo** [pmodels/argobots#12] opened 2017-01-19 17:15 UTC
Question from Liwei (Intel): Are you aware of any tools or methods that can print stack traces of all ULTs in a core dump? I have once encountered a deadlock among ULTs of the same ES. Although the very issue was easy enough to see with only traces of the active ULT, it would be more convincing if I could easily access the stack traces of the inactive ULTs too.

**Comment by shintaro-iwasaki** [comment] 2018-09-07 16:11
ULT dumps should be very useful for debugging. We can easily add a function printing a stack of a single ULT.
```
ABT_info_print_thread_stack(FILE *fp, ABT_thread thread);
```
There is no performance loss to support this feature. We will implement it in very near future.

___

However, there is a challenge to print *all* ULTs in the system.
```
ABT_info_print_all_thread_stacks(FILE *fp);
```

- Listing all ULTs in a pool.
Since Argobots allows users to implement their own pools, there is no general and portable way to list all the elements in the pool.
(See https://github.com/pmodels/argobots/blob/master/src/include/abt.h.in#L322)
One naive idea is that we do the *best effort* to print all the ULTs in a pool by repeating `pop`,
but it can cause a deadlock if a user-defined pool has a complicated synchronization system (e.g., https://github.com/pmodels/argobots/pull/49)

___

I came up with four ways to address this issue.

1. Create a new debug option to enable dumping all ULTs in the system.
Idea: keep track of all ULTs created in Argobots separately and print them when needed.
Pros: perfectly work with user-defined pools.
Cons: it degrades performance (maybe significantly), so this functionality will be disabled by default.

2. Print all ULTs in the pool only if these pools are predefined.
Idea: add new functionality to existing predefined pools.
Pros: no overheads to support it, so this functionality can be enabled by default.
Cons: it does not work with user-defined pools. This solution looks ad hoc a bit.

3. Add new pool functions.
Idea: create a new pool function to forcibly list all elements in pools (such as `pool_list_all_functions`)
Pros: straightforward
Cons: it needs API change which might hurt compatibility. This functionality is not general. It might narrow the pool design.

4. Give up and ask users to implement their own.
Idea: Argobots only provides `ABT_info_thread_stack(FILE *fp, ABT_thread thread);`.
Pros: simple
Cons: users need to implement their own.

It depends on use cases, but the first option looks good to me. I note Argobots has a similar mechanism for Valgrind support.

I am happy if anyone gives me feedback.

**Comment by johannlombardi** [comment] 2018-09-12 06:59
Thanks Shintaro for the detailed explanation. The use case on our side is to debug in a production environment (e.g. the service is stuck and we want to dump all ULTs to understand what is going on). As a result, I don't think that option 1 is viable for us since we won't be able to enable this debug mode in production.
To me, the best approach is option #3 where you extend ABT_pool_def with a new function to list all ULTs in a pool. Then you implement such handler for the default pool and let the user decide whether they want to support this functionality for their specific pool implementation. If this handler isn't implemented, then you just skip this pool and write a message in the output file saying that this functionality isn't supported by the pool implementation. I really don't think it can hurt compatibility since we are just adding a new feature. Thoughts?

**Comment by shintaro-iwasaki** [comment] 2018-09-12 14:08
Thank you for your comment. I understand your use case. The first option seems inappropriate,

___

About 3, as you pointed out, it won't hurt the performance if the implementation is optional, but it slightly hurts compatibility. A user passes an object containing user-defined pool functions to `ABT_pool_create()` like this:
```
ABT_pool_def def;
def.p_push = user_defined_push_f;
def.p_pop = user_defined_pop_f;
// def.p_list_all = user_defined_list_all_f;
ABT_pool_create(&def, [...]);
```
In this case, a new feature (say `pool_print_all()`, or `p_print_all()` in the code) is uninitialized and it causes segmentation fault when `pool_print_all()` is called. Of course, there are several ways to solve this issue (e.g., ask users to zero-clear the ABT_pool_def, or provide an initialization function such as `ABT_pool_def_create()`), while it still hurts compatibility anyway.

Currently, I haven't heard that anyone uses the custom pool feature, so I think no one opposes a new feature.

___

The other problem is a new pool function (for example `pool_print_all()` in the case above). I am thinking the following function.
```
void pool_print_all(void (*print_f)(ABT_unit *));
```
I note that this function can be used to print IDs of units in the pool, which is also useful to debug deadlocks or analyze dynamic load balancing and locality. However, the functionality might be too general, since it is quite similar to `map` or `apply`. If someone has idea, please join the discussion.

___

No matter how the pool implementation will be, I think we will finally provide the following functions. I hope they suffice.
```
ABT_info_print_thread_stack(FILE *fp, ABT_thread thread);
ABT_info_print_all_thread_stacks_in_pool(FILE *fp, ABT_pool pool);
ABT_info_print_all_thread_stacks_in_sched(FILE *fp, ABT_sched sched);
ABT_info_print_all_thread_stacks_in_xstream(FILE *fp, ABT_xstream xstream);
ABT_info_print_all_thread_stacks(FILE *fp);
```

**Comment by bfaccini** [comment] 2018-09-13 09:33
Hello,
I am working with Johann and I have some more comments/questions.

In ABT_info_print_thread_stack(), do you intend to unwind the ULT stack from its current/saved context ? And if yes, will you need to implement your own mechanism or there is some existing you may use ?

Will the ABT_info_print_all_thread_stacks[,_in_pool,_in_sched,_in_xstream]() functions work in a complementary/hierarchicaly way ? Will they try to be in a coherent state before to parse the corresponding and current set of ULTs?

**Comment by shintaro-iwasaki** [comment] 2018-09-13 13:43
@johannlombardi. Thank you! The implementation itself I plan (except stack unwinding if supported) should not be complicated. I hope I can make a prototype soon (hopefully within next week).

___

@bfaccini. We won't support stack unwinding for now. What I am thinking is simply printing a stack like this:
```
void ABT_info_print_thread_stack(FILE *fp, ABT_thread thread) {
  ABTI_thread *p_thread = ABTI_thread_get_ptr(thread);
  if (p_thread->attr.stacksize)
    fwrite(p_thread->attr.p_stack, sizeof(char), p_thread->attr.stacksize, fp);
}
```
We know it is not human friendly, while it should be better than nothing for debugging.
The very next PR won't include stack unwinding. However, it should be very useful for debugging, and can be a separate commit.

___

About coherence, there is no way to pause other schedulers in Argobots for now, so Argobots just does the best effort. For example, if the program suffers from livelock, printed ones might not be a coherent snapshot. The output of these functions might be slightly different because a pool can be shared among execution streams and a scheduler can be also shared in case where a stackable scheduler is pushed into a shared pool. Higher-level functions (`all_thread_stacks` > `all_thread_stacks_in_xstream` > ... ) will eliminate the duplication and show more consistent results.

It might be possible to stop the other execution streams by sending a signal, but there might be a significant side effect. It won't be added in the next PR.

I note that the current technique won't show currently running ULTs, suspended ULTs (e.g., `ABT_self_suspend` and `ABT_thread_join`), and ULTs that are about to run.

**Comment by shintaro-iwasaki** [comment] 2018-09-17 01:27
The current WIP PR contains all features I planned to implement.
The output looks like this, while `[...]` means my manual omission.
<details><summary>Output (collapsed) </summary>
<p>

```
= xstream[0] (0x1cd37d0) =
main_sched : 0x1cd3980
  pools[0] : 0x1cd3890
= xstream[1] (0x1cd3d90) =
main_sched : 0x1cd3cd0
  pools[1] : 0x1cd3c10
= xstream[2] (0x1cd4170) =
main_sched : 0x1cd40b0
  pools[2] : 0x1cd3fc0
= xstream[3] (0x1cd4550) =
main_sched : 0x1cd4490
  pools[3] : 0x1cd43a0
== pool (0x1cd3890) ==
=== ULT (0x7f0c18dfe020) ===
id    : 0
stack :
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[...]
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 f4 c0 ae 1b 0c 7f 00 00
fc 1d e2 18 0c 7f 00 00 43 2b 76 1b 0c 7f 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 51 00 21 b2 d9 d1 ac
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
80 1f 00 00 7f 03 00 00 20 1e e2 18 0c 7f 00 00
01 00 00 00 00 00 00 00 60 1e e2 18 0c 7f 00 00
29 a5 c6 70 00 00 00 00 60 1e e2 18 0c 7f 00 00
b0 1e e2 18 0c 7f 00 00 68 23 b0 1b 0c 7f 00 00
00 00 00 00 00 00 00 00 9d 13 40 00 00 00 00 00
3c 8d 6d 7a 54 8f 58 4b ec 89 22 54 18 1b e9 6d
db 7f 43 38 5c a4 44 76 02 f9 ff 32 1a 48 4a 68
fe 78 94 57 43 bb 9a 74 fb 40 c2 3d fa 26 a0 1b
aa de a1 79 3a c3 c6 75 fb 85 e6 12 29 a5 c6 70
00 00 00 00 00 00 00 00 45 13 40 00 00 00 00 00
00 00 00 00 00 00 00 00 00 51 00 21 b2 d9 d1 ac
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 e0 df 18 0c 7f 00 00 38 54 b0 1b 0c 7f 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 f1 59 b0 1b 0c 7f 00 00
=== ULT (0x7f0c18dfe120) ===
id    : 1
stack :
[...]
=== ULT (0x7f0c18dfe220) ===
id    : 2
stack :
[...]
== pool (0x1cd3c10) ==
=== ULT (0x7f0c18dfe720) ===
id    : 3
stack :
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[...]
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 51 00 21 b2 d9 d1 ac
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
08 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
80 1f 00 00 7f 03 00 00 20 d7 e3 18 0c 7f 00 00
08 00 00 00 00 00 00 00 60 d7 e3 18 0c 7f 00 00
c3 ac 07 3f 00 00 00 00 60 d7 e3 18 0c 7f 00 00
b0 d7 e3 18 0c 7f 00 00 68 23 b0 1b 0c 7f 00 00
00 00 00 00 00 00 00 00 9d 13 40 00 00 00 00 00
20 2e c3 3f 23 e8 c0 49 85 36 d5 14 6c 85 0f 23
fb 85 aa 6e b2 ec 06 3f 07 48 59 3b 04 23 aa 6c
f4 2f 7c 3f ec 3b 41 25 0b 0b 18 17 b9 28 93 57
20 5e 20 5d ba a8 cc 11 86 ab 32 4d c3 ac 07 3f
00 00 00 00 00 00 00 00 45 13 40 00 00 00 00 00
00 00 00 00 00 00 00 00 00 51 00 21 b2 d9 d1 ac
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 e7 df 18 0c 7f 00 00 38 54 b0 1b 0c 7f 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 f1 59 b0 1b 0c 7f 00 00
[...]
```
</p>
</details>

___

There are several issues.
1. It cannot be called in a signal handler. If you want to invoke this function in a signal handler (Ctrl + C), much more implementation efforts are needed.
2. Some thread stacks are not shown. The following cases are considered:
*  Main ULT which executed `ABT_initialize()`, since it is run on pthreads.
*  Threads that are currently running.
*  Threads that are handled in schedulers, It depends on timing.
*  Threads that suspend (e.g., `ABT_thread_join` and `ABT_thread_suspend`)
*  Threads stored in pools associated with stacked schedulers, although I think very few people use the stackable scheduler feature. 
3. The raw stack looks very useless. We would be happy if you know how to unwind stacks.

I would appreciate hearing your feedback.

**Comment by bfaccini** [comment] 2018-09-17 10:14
Hello,
Thanks for all of this, it looks already very promising!
I have some more questions/comments.

> It cannot be called in a signal handler.
Is this because of any risk to dead-lock on gp_ABTI_global->lock spin-lock ?? If this is the case, then why don't you better use a method (some new ABTI_spinlock_try() method?) that will try to acquire the lock but not block if lock is busy ? In our case, we intent to use this feature from a signal handler that will only be handled by our main thread which is basically idle after it has made his initialization duty (including ABT_init()). Doing so we expect to dump all stacks upon demand/need using SIG_USR1 signaling.

> We would be happy if you know how to unwind stacks
I think that you could have a look to libunwind (https://www.nongnu.org/libunwind/). It could be used  almost as is, if not using fcontext but preferably use glibc ucontext stuff... And it handles the debug-info/DWARF stuff too.

**Comment by shintaro-iwasaki** [comment] 2018-09-17 13:12
Thank you for your feedback!

1. Signal handler
As you know, signal-safe functions are very limited. If we call it in a signal handler, we need to very carefully implement it and clarify it in the document (or code). For example, `fprintf` we use to print data is not safe.
http://man7.org/linux/man-pages/man7/signal-safety.7.html
We need to impose this restriction on a pool function (`pool_print_all`) as well, making things more complicated. If this feature is really needed, I have to reconsider the current design. I note that keeping pool data consistent at any given point is also tough. For example, linked list data might be broken while changing pointers. I am happy if it can be avoided on your side.

1. libunwind
Thank you for your information. I will take a look at it. Now I am thinking that using this is a separate PR. I will investigate it after fixing the design of this.

**Comment by bfaccini** [comment] 2018-09-18 08:52
About "keeping pool data consistent at any given point", I think that using a signal handler would help to stop at least one xstream and then we could implement a mechanism to stop/park other xstreams during next context switch/yield.

**Comment by shintaro-iwasaki** [comment] 2018-09-18 14:01
As far as my understanding, there are the following issues to invoke `ABT_info_print_all_thread_stacks` in a signal handler.
1. Signal safety in Argobots
Since Argobots hasn't taken care of signal safety, we need to identify which Argobots functions are (or can be) signal safe. As I pointed out, `fprintf` is not signal safe, so I can't call it in a signal handler.
1. [Design] Signal safety requirement for user-defined pools
User-defined pools can also provide `pool_print_all`. Although this feature is optional, do we need the requirement of signal-safety for user-defined pools?
1. Pool data consistency and interruption
The execution stream interrupted by a signal might be performing pool operations. It is very difficult to guarantee that I can list up such a pool. For example, I am not sure whether I can correctly list up elements in the default Argobots FIFO queue even if that the execution stream was interrupted while performing `p_pool_push`.
It is not practical to ask for user-defined pools. That requirement is also burdensome even for the Argobots developers to implement better pre-defined pools in future (e.g., lock-free FIFO queues)
1. Pool data consistency and multi-threading
Other execution streams might be modifying pools. It should be addressed if your idea works.

IMO, "1. Create a new debug option to enable dumping all ULTs in the system", which I mentioned in my first comment, is practical if we really want to dump all stacks in a signal handler.

@bfaccini 
I might misunderstand your last comment, but if it is okay to wait for other execution streams (i.e., context switching), we don't need to call `ABT_info_print_all_thread_stacks` in a signal handler. For example, schedulers must periodically call `ABT_sched_has_to_stop` if schedulers are running (e.g., no spin-lock type deadlock in ULTs). We can safely stop all the other execution streams by checking a flag (e.g., `g_stop_and_print_all_thread_stacks=1`) in `ABT_sched_has_to_stop` and call print functions in user space. One can set this flag in a signal handler (and need to resume the interrupted execution stream).

Of course, this solution does not work if ones want to debug a critical error (e.g., illegal memory access). However, if the debug target is "deadlock", the solution above might be sufficient. I am waiting for your comment.

**Comment by bfaccini** [comment] 2018-09-19 13:33
In fact and thinking more about it after reading your comments/questioning, I think what could be done is to ensure our main thread starting the application which will use Argobot internally will be the only one able to catch, let say SIGUSR1, signal.

If we can then ensure that all ESs/xstreams can be parked, like by setting a specific flag/barrier to be checked in all accurate places of Argobot low-level scheduling mechanisms (similar, but may be more widely, to what you suggest with ABT_sched_has_to_stop()/g_stop_and_print_all_thread_stacks=1), then it should be ok for the signal handler to run ABT_info_print_all_thread_stacks(), right ?

I agree this could only work if there is no running ULTs "deadlock" or no current ULT looping/hung, but even during these last scenarios/cases the ULTs stacks dump should be safe ?

To be honest, I still don't understand why user-defined pools could be a problem as the way to retrieve all ULTs in pool should use the same pool->[unit->ULT,...] linkage ? Can you better detail/explain ? BTW, I don't understand why you think the mechanism/methods to dump all ULTs and their stacks can be customized, when it should be generic IMO.

**Comment by shintaro-iwasaki** [comment] 2018-09-19 14:11
Thank you for your questions and comments.

1. Custom pool.
Argobots offers a concept of user-defined pool, or custom pool. For example, users can implement a pool using lock-free or wait-free algorithm for a highly contended case. Argobots will provide better pools by default in future (for example, an algorithm for MPSC).
I don't want to narrow choices of pool algorithms by adding a new function or a new restriction. "Listing all elements in a pool without any side effects" (+ signal safety) (+ keeping consistent data at any point) is not trivial.
For example, a pool using mutex (= `FIFO-WAIT`) or its improvement in future might not satisfy signal-safety. I am not sure current doubly-linked pool (=`FIFO`) can be read at any time (e.g., traverse linked-list after interrupting an execution stream modifying that pool).
I am against imposing strong restrictions for pools so that users can easily implement their own pools, and also Argobots developers can easily implement better pools in future. In that sense, if Argobots would have only a single type of pool, we might somehow implement an extremely carefully designed pool (=signal safe and data-consistent at any point).

1. Safety of ULT stack dump.
My writing might be confusing. If *all* execution streams are stopped in a certain user-space function, we can safely dump ULT stacks. The important point is that the real print function is *not* called in a signal handler. Pseudo code is like this
```
// This function must be signal safe. It is exceptional in Argobots. All the other Argobots functions are not signal safe.
void ABT_info_set_print_all_thread_stacks_flag() {
  g_print_all_thread_stacks_flag = 1;
}

// Scheduler side
ABT_bool ABT_sched_has_to_stop(...) {
  if (g_print_all_thread_stacks_flag) {
    barrier();
    if (is_master())
      ABTI_info_print_all_thread_stacks(); // This function dumps.
    g_print_all_thread_stacks_flag = 0;
    barrier();
  }
  return [...];
}
void sched_run(...) {
  while (1) {
    [...]; // run work units in pools.
    if (ABT_sched_has_to_stop(...))
      return;
  }
}

// Signal handler (maybe in user code)
void singal_handler(...) {
  ABT_info_set_print_all_thread_stacks_flag();
  // IMPORTANT! resume the interrupted execution stream.
}
```
So this mechanism does not work when we cannot resume the interrupted execution stream (e.g., signal is invoked by illegal memory access).

As you pointed out, we can increase a checkpoint (`if (g_print_all_thread_stacks_flag)`), but it adds a branch, so we don't want to add many (for example, every time `ABT_thread_run_unit` is called).

**Comment by bfaccini** [comment] 2018-09-20 13:14
\> So this mechanism does not work when we cannot resume the interrupted execution stream (e.g., 
\> signal is invoked by illegal memory access).
I wrote in a comment before that we only want to trigger this feature live by using SIGUSR1 

In addition to the mechanism you have described with you pseudo-code snippet, I think the case where a xstream is hung or looping, highly probably running a buggy ULT context, must be handled and possibly after waiting for a reasonable time in the barrier(). Then it should be decided to continue anyway in dumping the stacks, since it is very likely that it should be safe to run through the lists of ULTs as no context-switch happens.

**Comment by shintaro-iwasaki** [comment] 2018-09-20 14:17
\> I wrote in a comment before that we only want to trigger this feature live by using SIGUSR1

I understood. As you know, `SIGUSR1` does not necessarily kill the target pthread. `ABT_info_set_print_all_thread_stacks_flag` can be called in a signal handler, so you can **trigger** the print function in a `SIGUSR1` signal handler. However, you need to **resume** the interrupted pthread afterwards. We are not sure whether it is possible in your case. Can I ask you (possibly again) that the execution stream can be resumed after being interrupted by `SIGUSR1`?

We agree that the signal safe printing function is absolutely better. However, it has some implementation difficulties as I mentioned.

The timeout mechanism you mentioned looks interesting, though we cannot guarantee that the printing function always succeeds. The print function should accept a timeout argument to forcibly print pool contents (and its ULT stacks) if the barrier is not released within a certain time.

**Comment by bfaccini** [comment] 2018-09-26 13:29
Presently we are running with a [p]thread/main() basically calling ABT_init() and then looping around sigwait() for a set of signals being handled to shutdown. As far as I understand this thread becomes the 1st ES/xstream main ULT/thread and its ULT context is being initialized based on its current stack content/pointer, right ? And as we don't use the 1st xstream for our own needs but only the ones that we create afterward, it should be ok to use it to handle these shutdown signals, and also SIGUSR1 that we want to use to print Argobot internal infos/structs (using already available ABT_info_print_[xstream,sched,pool,thread]() API) along with all ULTs stacks dump (using the future methods to be added for this issue), am I right again?

Yes, I really think that this time-out mechanism must be implemented to handle all situations.

**Comment by shintaro-iwasaki** [comment] 2018-09-26 18:17
Thank you for your comment, and sorry for long reply.
1. The thread calling `ABT_init()` becomes a master (=rank 0) execution stream. Is it true?
Yes.
2. The 1st execution stream can handles these shutdown signals. Is it true?
Any execution streams can catch signals. Argobots itself is unaware of signal.
3. ES interrupted by `SIGUSR1` can dump all (any info, then stack etc). Is it true?
Catching a signal is okay, but no Argobots functions are signal-safe. Argobots functions are not allowed to be called in a signal handler (including `ABT_info_print_xstream()` you mentioned)

___
There are three issues to call ABT functions in a signal handler.
1. **[Signal safety]**. Making all the (necessary) functions signal-safe is not easy. Many libc functions are not signal-safe (e.g., `fprintf()`). In addition, all the functions called in the signal-safe Argobots functions need to be signal-safe, making future maintenance difficult.
2. **[Intermediate pool state]** The pool contents are valid before and after the normal pool operations (e.g., `pool_push`), but the contents can be in an intermediate state during the operation (e.g., during `pool_push`). It is potentially dangerous to list all the elements in an intermediate state pool. In the worst case, it can cause `SEGV` (e.g., due to failing pointer traversal)

3. **[Future pools] (user-defined pool and future built-in pool)** Adding 1 and 2 requirement makes future pool design difficult. I think I am fully understanding those restricts and thus I am able to fix the current default pools. However, I am not sure if others who want to use a user-defined pool can do the same thing. It also might narrow the future built-in pools. For example, I am not sure I can do such a feat for a sophisticated state-of-the-art lock-free queue.

___

That's why we cannot easily implement a print function that can be called in a signal handler. However, thanks to your comments and suggestions, we now have better understanding of your situation. Could you please check the renewed proposals again?

1. Destructive "best effort" print
Run a print function in a signal handler. This function does best efforts (e.g., use timeout or synchronization). Still, we cannot guarantee that it always works correctly as ones expect. In the worst case, it causes `SEGV` or some critical errors. In other words, after calling this function, it is not guaranteed that the program continues (even if the interrupted ES does not do pool operations like in your case).
- Pros: The print function can be called in a signal handler.
- Cons: We cannot guarantee that it always works correctly or runs without any errors in general. It might cause `SEGV`, so we cannot guarantee that this function successfully returns.

2. Only for debug print
Add a mechanism to keep track of ULTs in pools safely and separately in a signal-safe manner.
- Pros: The print function can be called in a signal handler. No failure. Complete data is shown.
- Cons: This feature will be disabled by default since performance is degraded (possibly 2x or more if the parallelism is fine-grained.)

3. User space print
Suspend (= "park") all the execution streams at a certain point in the user space.
- Pros: The print "flagging" function can be called in a signal handler. No failure. Complete data can be shown.
- Cons: All the execution streams must reach "a certain point" after setting a flag. If the signal is called because of a critical reason (e.g., illegal memory access) and the program cannot be resumed, this mechanism is useless.

___

The ideal solution is "the best effort print that never fails". We don't know how often the best effort fails in reality. This feature is very hard to debug, while we cannot guarantee the success by design.

Doesn't the third idea work in your case? We are happy to hear your feedback.

**Comment by bfaccini** [comment] 2018-09-27 09:20
Yes, third idea is ok, but with the barrier timeout case handling (for looping/hung ULT situation).

Then with this mechanism, and our use case utilization of it in the 1st/rank-0 ES solo thread/ULT itself only sigwait()'ing for shutdown signals and SIGUSR1 we have choosed to trigger Argobot infos/stacks dump in a specific file, there should be no signal-safety related issue.

**Comment by shintaro-iwasaki** [comment] 2018-09-27 13:28
We understand. The next prototype will employ the timeout mechanism you proposed so that it can print something for the dead lock situation.

There is no signal-safety issue in your case and is expected to work properly. I note that in general at least one ES (in your case, maybe the first ES) must check a certain Argobots event (i.e., `ABT_sched_has_to_stop()`, which is invoked if `ABT_thread_yield()` is called in the `sigwait()`'ing loop). Nothing will be shown if all ESs hung.

**Comment by shintaro-iwasaki** [comment] 2018-09-28 22:13
We updated the PR (#68). We added two tests reflecting two use cases.

1. `info_stackdump`: timeout is unnecessary and thus disabled.
https://github.com/pmodels/argobots/blob/75fb0ae984c9f71b42fb13fefe77263b575f3a06/test/basic/info_stackdump.c
2. `info_stackdump2`: timeout works (some ESs hung, but at least one ES runs `ABT_xstream_check_events()` periodically)
https://github.com/pmodels/argobots/blob/75fb0ae984c9f71b42fb13fefe77263b575f3a06/test/basic/info_stackdump2.c

I hope this improved mechanism work in your cases.

Though it is not a problem in your case, I think the condition "at least one ES must reach `ABT_xstream_check_events()`" might be too strict. I am thinking a monitor thread to solve this issue (Pthreads-based thread only for "monitoring", which is mostly sleeping).

**Comment by bfaccini** [comment] 2019-04-29 20:52
When will changes for this issue #12 and from associated PR #68 become available ??

**Comment by shintaro-iwasaki** [comment] 2019-04-30 02:33
Sorry for leaving this issue for a long time. We will give this issue high priority, but please wait for additional a few weeks for the review and approval process.

**Comment by shintaro-iwasaki** [comment] 2019-05-10 21:49
As #68 and #98 are merged, Argobots now has stack trace features, so I will close this issue.

However, the current implementation prints raw call stack. I created a new issue (#101) to track this issue.

**Closed by shintaro-iwasaki** 2019-05-10 21:49 UTC
